//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Movie_API.Models
{
    using System;
    
    public partial class Movie_Insert_Param
    {
        public string Movie_name { get; set; }
        public int Release_year { get; set; }
        public string Description { get; set; }
        public string Type_name { get; set; }
        public decimal Rate { get; set; }
        public decimal Popularity { get; set; }
        public string Source_name { get; set; }
    }
}
